---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: resume
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/component: personal-website
    app.kubernetes.io/managed-by: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:cmoore1776/resume.git
    targetRevision: main
    path: chart
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: resume

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
